include:
  - board: seeeduino_xiao_ble
    shield: totem_left rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: totem_right rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: settings_reset
  - board: seeeduino_xiao_ble
    shield: totem_btleft rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: totem_btright rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: totem_dongle rgbled_adapter
